### ISSUE TITLE
Alt + shift + Roller do not work on MAC machines.

### ISSUE THREAD

**Issue by Jacobweasley** [kregerl/Inventory-Hotswap#3]
because  when ever press shift +  Scroll mouse it's horizontal scrolling in Macintosh , so the bar switch with mouse did't work . Only the Shortcut key work on Mac . can you add a switchable key binding like Alt key does.
pls.

**Comment by kregerl** [comment]
Fabric 1.17 release has an option that disables sneak to display full inventory by default and adds a keybind to replace sneaking. Will port to forge when 1.17 is out.
