### ISSUE TITLE
Please reconsider CurseForge third-party distribution setting

### ISSUE THREAD

**Issue by copygirl** [kregerl/Inventory-Hotswap#7]
Apologies for the lack of a personalized message, but I will be contacting a number of modders today.
Your mod, Inventory Hotswap, is one of the few that can't be downloaded by third-party launchers and other tools.
With the following GitHub Gist I would like to try changing your mind, and those of other creators.

https://gist.github.com/copygirl/7d45bad739453d2be61138cebafce04c

Thank you for your work! :green_heart:

**Comment by kregerl** [comment]
I didn't even know this was disabled, I use polymc myself. I've enabled it for all my mods.

**Comment by copygirl** [comment]
Sweet, thank you!
